# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Veterinary Defence Association
email: info@vetdefenceco.com
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://veterinary-defence-association.org" # the base hostname & protocol for your site
twitter_username: vetdefenceco
github_username:  vetdefenceco

# Build settings
markdown: kramdown

vda:
  - iso: au
    country: Australia
    url: vda-australia.org
  - iso: hk
    country: Hong Kong
    url: vda-asia.org
  - iso: za
    country: South Africa
    url: vda-southafrica.org
  - iso: us
    country: United States
    url: vda-america.org
